apiVersion: v1
kind: Service
metadata:
  name: starbound-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 21025
      targetPort: 21025
  selector:
    app: starbound
  externalTrafficPolicy: Local
